"""Deterministic synthetic worlds for adversarial TIAMAT discovery tests.

These worlds deliberately encode different causal geometries without teaching the
selector which observable is supposed to win.  They provide labels plus named
held-out probability streams so the tournament can be tested independently of
any particular model-fitting implementation.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping


@dataclass(frozen=True, slots=True)
class AdversarialWorld:
    """A small held-out world with an explicit generating mechanism label."""

    name: str
    labels: tuple[int, ...]
    predictions: Mapping[str, tuple[float, ...]]
    truth_mechanism: str


def _labels(n: int = 20) -> tuple[int, ...]:
    return tuple(i % 2 for i in range(n))


def _signal(labels: tuple[int, ...], low: float = 0.10, high: float = 0.90) -> tuple[float, ...]:
    return tuple(high if y else low for y in labels)


def _weak_rank(labels: tuple[int, ...]) -> tuple[float, ...]:
    return tuple(0.51 if y else 0.49 for y in labels)


def _inverse(labels: tuple[int, ...]) -> tuple[float, ...]:
    return tuple(0.90 if not y else 0.10 for y in labels)


def _regime_conflict(labels: tuple[int, ...]) -> tuple[float, ...]:
    """Fit regime 1 correctly and regime 2 inversely, forcing global conflict."""
    midpoint = len(labels) // 2
    values: list[float] = []
    for i, label in enumerate(labels):
        correct = i < midpoint
        values.append(0.90 if (label == 1) == correct else 0.10)
    return tuple(values)


def _interaction_world(n: int = 20) -> tuple[tuple[int, ...], dict[str, tuple[float, ...]]]:
    """Construct a genuine interaction where neither component alone predicts Y.

    A and B are independent balanced binary components.  The label is XOR(A, B),
    so each component has zero marginal predictive information while their joint
    interaction is perfectly informative.  A_x_B is *computed* from the two
    component probabilities rather than being handed the labels.
    """
    a_state = tuple(i % 2 for i in range(n))
    b_state = tuple((i // 2) % 2 for i in range(n))
    labels = tuple(a ^ b for a, b in zip(a_state, b_state))

    # Use high-confidence component probabilities while preserving zero marginal
    # information.  The XOR composition is therefore strongly informative without
    # ever consulting the labels.
    a = tuple(0.95 if value else 0.05 for value in a_state)
    b = tuple(0.95 if value else 0.05 for value in b_state)
    # P(A xor B) under the two component probabilities.
    axb = tuple(pa * (1.0 - pb) + (1.0 - pa) * pb for pa, pb in zip(a, b))
    return labels, {"A": a, "B": b, "A_x_B": axb}


def build_adversarial_worlds() -> tuple[AdversarialWorld, ...]:
    """Return deterministic worlds covering distinct failure modes."""
    y = _labels()
    neutral = (0.50,) * len(y)
    strong = _signal(y)
    weak = _weak_rank(y)
    inverse = _inverse(y)

    # The first half carries one mechanism and the second half another. A
    # globally conflicting candidate should not be promoted merely for local fit.
    regime_conflict = _regime_conflict(y)

    # Genuine interaction-only world: neither A nor B is predictive by itself;
    # Y is generated by XOR(A, B), and A_x_B is calculated from A and B.
    interaction_labels, interaction = _interaction_world()

    return (
        AdversarialWorld("clean_state", y, {"state": strong, "noise": neutral}, "state"),
        AdversarialWorld("auc_trap", y, {"state": weak, "noise": neutral}, "none"),
        AdversarialWorld("inverse_signal", y, {"state": inverse, "noise": neutral}, "none"),
        AdversarialWorld("calibration_deception", y, {"overranked": weak, "calibrated": strong}, "calibrated"),
        AdversarialWorld("interaction_only", interaction_labels, interaction, "A_x_B"),
        AdversarialWorld("delayed_trajectory", y, {"instant": weak, "delayed": strong}, "delayed"),
        AdversarialWorld("regime_conflict", y, {"global": regime_conflict, "neutral": neutral}, "none"),
        AdversarialWorld("no_signal", y, {"A": neutral, "B": neutral, "C": neutral}, "none"),
        AdversarialWorld("redundant_signal", y, {"state": strong, "damage": strong, "noise": neutral}, "state_or_damage"),
        AdversarialWorld("path_signal", y, {"path": strong, "instant": weak}, "path"),
        AdversarialWorld("momentum_signal", y, {"initial_momentum": strong, "residual": weak}, "initial_momentum"),
        AdversarialWorld("resistance_signal", y, {"resistance": strong, "flow": weak}, "resistance"),
    )
