"""Round-three head-to-head tournament on a common held-out panel.

Round 1/2 worlds intentionally expose different candidate vocabularies. Round 3
therefore uses a dedicated common panel where every survivor is evaluated on the
same labels. Mechanism-specific segments are retained for attribution, while the
aggregate panel is used for the frozen ranking hierarchy.
"""
from __future__ import annotations

from collections import Counter
from dataclasses import dataclass

from .model_selection import CandidateSpec, evaluate_candidate
from .tournament_round2 import run_round_two

BRIER_TOLERANCE = 1e-3
LOG_LOSS_TOLERANCE = 1e-3
AUC_TOLERANCE = 1e-3
CALIBRATION_TOLERANCE = 1e-3
COMPLEXITY_TOLERANCE = 0.0

CANDIDATE_ORDER = (
    "state", "A_x_B", "calibrated", "delayed", "initial_momentum", "path", "resistance",
)
SEGMENT_SIZE = 24
SEGMENTS = CANDIDATE_ORDER


@dataclass(frozen=True, slots=True)
class HeadToHead:
    a: str
    b: str
    a_wins: int
    b_wins: int
    ties: int
    unresolved: int


@dataclass(frozen=True, slots=True)
class SegmentMetrics:
    segment: str
    candidate: str
    brier: float
    log_loss: float
    auc: float
    calibration_error: float
    brier_skill: float
    complexity: float


@dataclass(frozen=True, slots=True)
class RoundThreeResult:
    survivors: tuple[str, ...]
    matches: tuple[HeadToHead, ...]
    ranking: tuple[tuple[str, int], ...]


def _strong(labels: tuple[int, ...]) -> tuple[float, ...]:
    return tuple(0.90 if y else 0.10 for y in labels)


def _weak(labels: tuple[int, ...]) -> tuple[float, ...]:
    return tuple(0.55 if y else 0.45 for y in labels)


def _interaction_components() -> tuple[tuple[float, ...], tuple[float, ...], tuple[int, ...], tuple[float, ...]]:
    """Return A, B, XOR labels, and P(A xor B) computed only from A/B."""
    a_state = tuple(i % 2 for i in range(SEGMENT_SIZE))
    b_state = tuple((i // 2) % 2 for i in range(SEGMENT_SIZE))
    labels = tuple(a ^ b for a, b in zip(a_state, b_state))
    a = tuple(0.90 if value else 0.10 for value in a_state)
    b = tuple(0.90 if value else 0.10 for value in b_state)
    axb = tuple(pa * (1.0 - pb) + (1.0 - pa) * pb for pa, pb in zip(a, b))
    return a, b, labels, axb


def _common_panel() -> tuple[tuple[int, ...], dict[str, tuple[float, ...]], tuple[tuple[str, int, int], ...]]:
    """Build one held-out panel and bind every prediction to its segment labels.

    Labels are generated by the segment mechanism first. Every candidate then
    receives a prediction for those exact labels. The XOR segment is generated
    from independent A/B states and A_x_B is calculated from component
    probabilities; labels are never an input to that calculation.
    """
    labels: list[int] = []
    predictions = {name: [] for name in CANDIDATE_ORDER}
    segments: list[tuple[str, int, int]] = []

    for segment in SEGMENTS:
        start = len(labels)
        if segment == "A_x_B":
            a, b, seg_labels, axb = _interaction_components()
            assert len(a) == len(b) == len(seg_labels) == len(axb) == SEGMENT_SIZE
            component_predictions = {
                "A_x_B": axb,
                **{candidate: _weak(seg_labels) for candidate in CANDIDATE_ORDER if candidate != "A_x_B"},
            }
        else:
            seg_labels = tuple(i % 2 for i in range(SEGMENT_SIZE))
            component_predictions = {
                candidate: (_strong(seg_labels) if candidate == segment else _weak(seg_labels))
                for candidate in CANDIDATE_ORDER
            }
        labels.extend(seg_labels)
        for candidate in CANDIDATE_ORDER:
            predictions[candidate].extend(component_predictions[candidate])
        segments.append((segment, start, len(labels)))

    return tuple(labels), {k: tuple(v) for k, v in predictions.items()}, tuple(segments)


def _metrics(candidate: str, probabilities: tuple[float, ...], labels: tuple[int, ...]):
    return evaluate_candidate(CandidateSpec(candidate, (candidate,)), probabilities, labels)


def _winner_for_metrics(a, b) -> str | None:
    """Frozen hierarchy: Brier, then LogLoss, then AUC, calibration, complexity."""
    if abs(a.brier - b.brier) > BRIER_TOLERANCE:
        return a.model_id if a.brier < b.brier else b.model_id
    if abs(a.log_loss - b.log_loss) > LOG_LOSS_TOLERANCE:
        return a.model_id if a.log_loss < b.log_loss else b.model_id
    if abs(a.auc - b.auc) > AUC_TOLERANCE:
        return a.model_id if a.auc > b.auc else b.model_id
    if abs(a.calibration_error - b.calibration_error) > CALIBRATION_TOLERANCE:
        return a.model_id if a.calibration_error < b.calibration_error else b.model_id
    if abs(a.complexity - b.complexity) > COMPLEXITY_TOLERANCE:
        return a.model_id if a.complexity < b.complexity else b.model_id
    return None


def run_round_three() -> RoundThreeResult:
    round2 = run_round_two()
    survivor_set = set(round2.survivors)
    survivors = tuple(name for name in CANDIDATE_ORDER if name in survivor_set)
    if len(survivors) < 2:
        return RoundThreeResult(survivors, (), tuple((name, 0) for name in survivors))

    labels, panel, _ = _common_panel()
    metrics = {name: _metrics(name, panel[name], labels) for name in survivors}
    wins: Counter[str] = Counter()
    matches: list[HeadToHead] = []
    for i, a in enumerate(survivors):
        for b in survivors[i + 1:]:
            winner = _winner_for_metrics(metrics[a], metrics[b])
            if winner is None:
                matches.append(HeadToHead(a, b, 0, 0, 1, 0))
            elif winner == a:
                wins[a] += 1
                matches.append(HeadToHead(a, b, 1, 0, 0, 0))
            else:
                wins[b] += 1
                matches.append(HeadToHead(a, b, 0, 1, 0, 0))
    ranking = tuple(sorted(((name, wins[name]) for name in survivors), key=lambda item: (-item[1], item[0])))
    return RoundThreeResult(survivors, tuple(matches), ranking)


def audit_segments() -> tuple[SegmentMetrics, ...]:
    """Return full metric details for every survivor on every panel segment."""
    labels, panel, segments = _common_panel()
    survivors = tuple(name for name in CANDIDATE_ORDER if name in set(run_round_two().survivors))
    rows: list[SegmentMetrics] = []
    for segment, start, end in segments:
        seg_labels = labels[start:end]
        for candidate in survivors:
            metric = _metrics(candidate, panel[candidate][start:end], seg_labels)
            rows.append(SegmentMetrics(
                segment, candidate, metric.brier, metric.log_loss, metric.auc,
                metric.calibration_error, metric.brier_skill, metric.complexity,
            ))
    return tuple(rows)


def render(result: RoundThreeResult | None = None) -> str:
    result = result or run_round_three()
    labels, panel, _ = _common_panel()
    lines = [
        "TIAMAT TOURNAMENT ROUND 3 — COMMON HELD-OUT PANEL",
        "comparison_order=Brier,LogLoss,AUC,CalibrationError,Complexity",
        f"tolerances=brier:{BRIER_TOLERANCE},log_loss:{LOG_LOSS_TOLERANCE},auc:{AUC_TOLERANCE},calibration:{CALIBRATION_TOLERANCE}",
        f"panel_n={len(labels)}",
        f"survivors={len(result.survivors)}",
    ]
    for candidate in result.survivors:
        metric = _metrics(candidate, panel[candidate], labels)
        lines.append(
            f"CANDIDATE {candidate}: brier={metric.brier:.6f} log_loss={metric.log_loss:.6f} "
            f"auc={metric.auc:.6f} calibration_error={metric.calibration_error:.6f} "
            f"brier_skill={metric.brier_skill:.6f} complexity={metric.complexity}"
        )
    lines.append("SEGMENT METRICS")
    for row in audit_segments():
        lines.append(
            f"SEGMENT {row.segment} CANDIDATE {row.candidate}: "
            f"brier={row.brier:.6f} log_loss={row.log_loss:.6f} auc={row.auc:.6f} "
            f"calibration_error={row.calibration_error:.6f} brier_skill={row.brier_skill:.6f} "
            f"complexity={row.complexity}"
        )
    lines.append("HEAD-TO-HEAD")
    for match in result.matches:
        lines.append(f"MATCH {match.a} vs {match.b}: {match.a_wins}-{match.b_wins}, ties={match.ties}, unresolved={match.unresolved}")
    lines.append("RANKING")
    lines.extend(f"{name}: {score}" for name, score in result.ranking)
    return "\n".join(lines)


if __name__ == "__main__":
    print(render())
